// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZdTA6vJd4i1bxDHHGAjZOvm9LhQgDp1s',
    appId: '1:316243308563:android:27572bc3baf9b64cf80fe6',
    messagingSenderId: '316243308563',
    projectId: 'scheduler-c1c6e',
    databaseURL: 'https://scheduler-c1c6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scheduler-c1c6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgso6sq79BQ2Dml-1-jukeMmNoTlevKD8',
    appId: '1:316243308563:ios:1a3366bfd24f88e7f80fe6',
    messagingSenderId: '316243308563',
    projectId: 'scheduler-c1c6e',
    databaseURL: 'https://scheduler-c1c6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'scheduler-c1c6e.appspot.com',
    iosBundleId: 'org.idbiintech.scheduler',
  );
}
